import React from 'react'
import Productslist from 'pages/Productslist'

const App = () => {
	const products = [

{
	GameTitle: 'Red Dead Redemption 2',
	GameGenre: 'Open Wolrd, RPG, Adventure',
	GamePrice: 39.99,
	oldPrice: 69.99,
	GameRating: 4.5,
	Edition: [`original`, `premiumPack`],
	GameImage: 'Red-dead-1.jpeg',
},
{
	GameTitle: 'God Of War 4',
	GameGenre: 'Open Wolrd, Adventure',
	GamePrice: 59.99,
	oldPrice: 89.99,
	GameRating: 4.5,
	Edition: [`original`, `extensionPack`, `premiumPack`],
	GameImage: 'gowa.jpeg',
},
{
	GameTitle: 'The Witcher 3',
	GameGenre: 'Open Wolrd, RPG, Adventure',
	GamePrice: 39.99,
	oldPrice: 79.99,
	GameRating: 5,
	Edition: [`original`, `extensionPack`, `premiumPack`],
	GameImage: 'thewitcher.jpeg',
},
{
	GameTitle: 'Valhalla',
	GameGenre: 'Open Wolrd, RPG, Adventure',
	GamePrice: 39.99,
	oldPrice: 79.99,
	GameRating: 4.5,
	Edition: [`original`, `extensionPack`, `premiumPack`],
	GameImage: 'valhalla.jpeg',
},
{
	GameTitle: 'GTA 5',
	GameGenre: 'Multi Gaming, Action, Open World',
	GamePrice: 14.99,
	oldPrice: 59.99,
	GameRating: 4,
	Edition: [`original`],
	GameImage: 'gta5.jpeg',
},
{
	GameTitle: 'The Last Of Us',
	GameGenre: 'Action, Horror',
	GamePrice: 39.99,
	oldPrice: 89.99,
	GameRating: 5,
	Edition: [`original`, `extensionPack`],
	GameImage: 'tlou.png',
},
{
	GameTitle: 'Village Resident Evil',
	GameGenre: 'Horror, Multi Gaming',
	GamePrice: 39.99,
	oldPrice: 69.99,
	GameRating: 4.5,
	Edition: [`original`],
	GameImage: 'village.jpeg',
},
{
	GameTitle: 'Fifa 21',
	GameGenre: 'Sport, Multi Gaming',
	GamePrice: 39.99,
	oldPrice: 89.99,
	GameRating: 4,
	Edition: [`original`, `premiumPack`],
	GameImage: 'fifa-21-1.jpeg',
},
{
	GameTitle: 'Horizon Zero Down',
	GameGenre: 'Adventure, Open World',
	GamePrice: 49.99,
	oldPrice: 99.99,
	GameRating: 4,
	Edition: [`original`, `premiumPack`],
	GameImage: 'horizonzerodown.png',
},
{
	GameTitle: 'Battlefield 5',
	GameGenre: 'Action, FPS',
	GamePrice: 29.99,
	oldPrice: 69.99,
	GameRating: 5,
	Edition: [`original`, `extensionPack`],
	GameImage: 'Battlefiels-V.jpeg',
},
{
	GameTitle: 'Ghost of Tshushima',
	GameGenre: 'RPG, Open World',
	GamePrice: 39.99,
	oldPrice: 89.99,
	GameRating: 5,
	Edition: [`original`, `extensionPack`, `premiumPack`],
	GameImage: 'Ghost-of-Tsushima.jpeg',
},
{
	GameTitle: 'CyberPunk 2077',
	GameGenre: 'Action, Open World',
	GamePrice: 59.99,
	oldPrice: 109.99,
	GameRating: 4,
	Edition: [`original`, `extensionPack`],
	GameImage: 'Cyberpunk.jpeg',
},
{
	GameTitle: 'Mortal Kombat',
	GameGenre: 'Action, Multi Gaming',
	GamePrice: 19.99,
	oldPrice: 59.99,
	GameRating: 3,
	Edition: [`original`, `extensionPack`],
	GameImage: 'mortalkombat.jpeg',
},
{
	GameTitle: 'Skyrim',
	GameGenre: 'Adventure, RPG, Open World',
	GamePrice: 39.99,
	oldPrice: 89.99,
	GameRating: 5,
	Edition: [`original`, `extensionPack`],
	GameImage: 'skyrim.jpeg',
},
{
	GameTitle: 'The Legend of Zelda',
	GameGenre: 'Adventure, Open World',
	GamePrice: 39.99,
	oldPrice: 89.99,
	GameRating: 4,
	Edition: [`original`,`premiumPack`],
	GameImage: 'thelegendofzelda.jpeg',
},
{
	GameTitle: 'The Sims 4',
	GameGenre: 'Lifestyle',
	GamePrice: 29.99,
	oldPrice: 69.99,
	GameRating: 4,
	Edition: [`original`, `extensionPack`],
	GameImage: 'sims4.jpeg',
},
{
	GameTitle: 'Detroit Become Human',
	GameGenre: 'Adventure',
	GamePrice: 39.99,
	oldPrice: 69.99,
	GameRating: 5,
	Edition: [`original`],
	GameImage: 'detroitbecomehuman.jpeg',
},
{
	GameTitle: 'Dark Souls 3',
	GameGenre: 'Adventure, RPG',
	GamePrice: 29.99,
	oldPrice: 69.99,
	GameRating: 4,
	Edition: [`original`, `extensionPack`, `premiumPack`],
	GameImage: 'Dark-Souls-3.jpeg',
},
{
	GameTitle: 'NBA 2K21',
	GameGenre: 'Multi Gaming, Sport',
	GamePrice: 9.99,
	oldPrice: 59.99,
	GameRating: 3,
	Edition: [`original`, `extensionPack`],
	GameImage: 'nba2K21.jpeg',
},{
	GameTitle: 'AC Brotherhood',
	GameGenre: 'Adventure, RPG',
	GamePrice: 9.99,
	oldPrice: 39.99,
	GameRating: 5,
	Edition: [`original`, `premiumPack`],
	GameImage: 'acbrotherhood.jpeg',
},
]

return (
	<Products data={products}/>
)
}